name: dart_mappable_example_freezed

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_mappable:
    path: ../../
  freezed_annotation: ^0.14.2

dev_dependencies:
  build_runner: ^2.0.5
  freezed: ^0.14.2