name: dart_mappable_workspace
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

workspace:
  - packages/dart_mappable
  - packages/dart_mappable_builder

dev_dependencies:
  melos: ^7.0.0

melos:
  ide:
    intellij:
      enabled: false
      
  command:
    bootstrap:
      usePubspecOverrides: true

  scripts:
    test:
      run: melos exec -- 'dart test'
      packageFilters:
        scope:
          - dart_mappable
          - package_comparison
    coverage:
      run: |
        melos exec -- 'dart test --coverage=coverage'
        melos exec -- 'dart pub global run coverage:format_coverage --check-ignore --packages=.dart_tool/package_config.json --report-on=lib --lcov -o "$MELOS_ROOT_PATH/coverage/lcov.info" -i ./coverage'
      packageFilters:
        scope: dart_mappable
    build:
      run: melos exec -- 'dart run build_runner build -d'
      packageFilters:
        scope:
    format:
      run: melos exec -- 'dart format . --set-exit-if-changed'
    analyze:
      run: melos exec -- 'dart analyze . --fatal-infos'
