name: dart_mappable_builder
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 4.6.0
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues
funding:
  - https://github.com/sponsors/schultek

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  analyzer: '>=7.5.9 <=8.0.0'
  ansicolor: ^2.0.1
  build: ^3.0.0
  collection: ^1.15.0
  dart_mappable: ^4.6.0
  dart_style: ^3.0.1
  glob: ^2.1.0
  path: ^1.8.0
  source_gen: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.14
  build_test: ^3.3.0
  lints: '>=1.0.0 <6.0.0'
  test: ^1.25.10
  
