name: dart_mappable
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 2.0.0-dev.10
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues
funding:
  - https://github.com/sponsors/schultek

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  meta: ^1.8.0
  type_plus: ^0.8.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_mappable_builder: ^2.0.0-dev.10
  lints: '>=1.0.0 <3.0.0'
  test: ^1.20.1
