name: dart_mappable
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 4.6.1
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues
documentation: https://pub.dev/documentation/dart_mappable/latest/topics/Introduction-topic.html
funding:
  - https://github.com/sponsors/schultek

environment:
  sdk: ">=3.7.0 <4.0.0"

topics:
  - json
  - data-class
  - codegen
  - build-runner

dependencies:
  collection: ^1.15.0
  meta: ^1.8.0
  type_plus: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder:
    path: ../dart_mappable_builder
  lints: ^5.0.0
  test: ^1.25.10
