name: package_comparison

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_json_mapper: ^2.2.7+5
  dart_mappable: ^4.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  test: ^1.22.1

dev_dependencies:
  build_runner: ^2.1.0
  dart_mappable_builder: ^4.3.0
  freezed: ^2.3.2
  json_serializable: ^6.8.0
  lints: ^2.0.0